version: '3.4'
services:
  web:
    build: .
    command: bundle exec rails server -b '0.0.0.0' -p 3000 -P /tmp/rails.pid
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  redis:
    image: "redis:6-alpine"
    ports:
      - 6379
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - 5432:5432

volumes:
  db_data:
  ruby-bundle-cache:
    external: true
