default: &default
  adapter: "redis"
  url: "<%= ENV.fetch("REDIS_URL") { "redis:6379/1" } %>"

development:
  <<: *default
  channel_prefix: "s7_08_development"

test:
  <<: *default
  adapter: "test"

production:
  <<: *default
  channel_prefix: "s7_08_production"
