default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  #pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "s7_08" } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "s7_08" } %>_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "s7_08" } %>_production
